    # =============================================================================
    # [DATA FILE ONLY]  (자동 분리됨)
    # 이 파일은 로직이 아니라 '튜닝 테이블/상수'만 담는 **데이터 모듈**입니다.
    # LLM 컨텍스트에는 기본적으로 포함하지 말고, 테이블을 수정/튜닝할 때만 열어보세요.
    #
    # 포함 데이터(요약):
    #   - SCHEME_BASE_OUTCOME_LABELS: {scheme: {base_action: {outcome: quality_label}}}
#   - ROLE_STAT_PROFILES: {scheme: {role: {stat_key: weight}}}
#   - GROUP_SCHEME_ROLE_WEIGHTS: {group_id: {scheme: {role: weight}}}
#   - OUTCOME_TO_GROUP / GROUP_FALLBACK / SCHEME_ALIASES: mapping tables
#   - 로직 파일: quality.py
    # =============================================================================

"""
Data tables for quality.py.

This module is intentionally data-heavy.
Avoid including it in LLM context unless you are editing the tables.
"""
from __future__ import annotations

from typing import Dict

# scheme -> base_action -> outcome -> label
SCHEME_BASE_OUTCOME_LABELS: Dict[str, Dict[str, Dict[str, str]]] = {'2-3 존디펜스': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'weak',
                      'PASS_KICKOUT': 'weak',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'Neutral',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'DHO': {'FOUL_DRAW_JUMPER': 'Neutral',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'weak',
                      'PASS_KICKOUT': 'weak',
                      'SHOT_3_CS': 'weak',
                      'SHOT_3_OD': 'Neutral',
                      'SHOT_MID_PU': 'Neutral',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                        'PASS_EXTRA': 'weak',
                        'PASS_KICKOUT': 'weak',
                        'SHOT_3_OD': 'Neutral',
                        'SHOT_MID_PU': 'Neutral',
                        'SHOT_RIM_CONTACT': 'tight',
                        'SHOT_RIM_DUNK': 'Neutral',
                        'SHOT_RIM_LAYUP': 'tight',
                        'SHOT_TOUCH_FLOATER': 'Neutral',
                        'TO_CHARGE': 'Neutral',
                        'TO_HANDLE_LOSS': 'Neutral'},
              'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                            'PASS_EXTRA': 'Neutral',
                            'PASS_SKIP': 'weak',
                            'SHOT_3_CS': 'Neutral',
                            'SHOT_MID_CS': 'Neutral'},
              'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                           'PASS_EXTRA': 'Neutral',
                           'PASS_KICKOUT': 'weak',
                           'SHOT_3_CS': 'Neutral',
                           'SHOT_MID_CS': 'Neutral'},
              'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_SKIP': 'weak',
                          'SHOT_3_CS': 'Neutral',
                          'SHOT_MID_CS': 'Neutral'},
              'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_KICKOUT': 'weak',
                      'PASS_SHORTROLL': 'Neutral',
                      'SHOT_3_CS': 'weak',
                      'SHOT_3_OD': 'Neutral',
                      'SHOT_MID_PU': 'Neutral',
                      'SHOT_RIM_DUNK': 'tight',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                         'PASS_EXTRA': 'weak',
                         'PASS_KICKOUT': 'weak',
                         'PASS_SKIP': 'weak',
                         'SHOT_POST': 'Neutral',
                         'SHOT_RIM_CONTACT': 'tight',
                         'TO_HANDLE_LOSS': 'Neutral'},
              'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'weak', 'SHOT_MID_CS': 'Neutral'},
              'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                                  'PASS_EXTRA': 'Neutral',
                                  'PASS_KICKOUT': 'Neutral',
                                  'SHOT_3_CS': 'Neutral',
                                  'SHOT_3_OD': 'Neutral',
                                  'SHOT_RIM_CONTACT': 'Neutral',
                                  'SHOT_RIM_DUNK': 'Neutral',
                                  'SHOT_RIM_LAYUP': 'Neutral',
                                  'SHOT_TOUCH_FLOATER': 'Neutral',
                                  'TO_HANDLE_LOSS': 'Neutral'}},
 'drop': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                  'PASS_EXTRA': 'Neutral',
                  'PASS_KICKOUT': 'Neutral',
                  'SHOT_RIM_CONTACT': 'tight',
                  'SHOT_RIM_DUNK': 'Neutral',
                  'SHOT_RIM_LAYUP': 'Neutral',
                  'SHOT_TOUCH_FLOATER': 'Neutral',
                  'TO_HANDLE_LOSS': 'Neutral'},
          'DHO': {'FOUL_DRAW_JUMPER': 'Neutral',
                  'FOUL_DRAW_RIM': 'tight',
                  'PASS_EXTRA': 'Neutral',
                  'PASS_KICKOUT': 'Neutral',
                  'SHOT_3_CS': 'Neutral',
                  'SHOT_3_OD': 'tight',
                  'SHOT_MID_PU': 'weak',
                  'SHOT_RIM_DUNK': 'Neutral',
                  'SHOT_RIM_LAYUP': 'tight',
                  'SHOT_TOUCH_FLOATER': 'Neutral',
                  'TO_HANDLE_LOSS': 'Neutral'},
          'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'Neutral',
                    'PASS_KICKOUT': 'weak',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'Neutral',
                    'SHOT_RIM_CONTACT': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_CHARGE': 'Neutral',
                    'TO_HANDLE_LOSS': 'Neutral'},
          'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_SKIP': 'Neutral',
                        'SHOT_3_CS': 'weak',
                        'SHOT_MID_CS': 'Neutral'},
          'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                       'PASS_EXTRA': 'Neutral',
                       'PASS_KICKOUT': 'Neutral',
                       'SHOT_3_CS': 'Neutral',
                       'SHOT_MID_CS': 'Neutral'},
          'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_SKIP': 'Neutral',
                      'SHOT_3_CS': 'weak',
                      'SHOT_MID_CS': 'Neutral'},
          'PnR': {'FOUL_DRAW_JUMPER': 'Neutral',
                  'FOUL_DRAW_RIM': 'tight',
                  'PASS_KICKOUT': 'weak',
                  'PASS_SHORTROLL': 'Neutral',
                  'SHOT_3_CS': 'weak',
                  'SHOT_3_OD': 'Neutral',
                  'SHOT_MID_PU': 'weak',
                  'SHOT_RIM_DUNK': 'Neutral',
                  'SHOT_RIM_LAYUP': 'tight',
                  'SHOT_TOUCH_FLOATER': 'neutral',
                  'TO_HANDLE_LOSS': 'Neutral'},
          'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                     'PASS_EXTRA': 'Neutral',
                     'PASS_KICKOUT': 'Neutral',
                     'PASS_SKIP': 'Neutral',
                     'SHOT_POST': 'Neutral',
                     'SHOT_RIM_CONTACT': 'tight',
                     'TO_HANDLE_LOSS': 'Neutral'},
          'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'Neutral', 'SHOT_MID_CS': 'Neutral'},
          'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                              'PASS_EXTRA': 'Neutral',
                              'PASS_KICKOUT': 'Neutral',
                              'SHOT_3_CS': 'Neutral',
                              'SHOT_3_OD': 'Neutral',
                              'SHOT_RIM_CONTACT': 'Neutral',
                              'SHOT_RIM_DUNK': 'Neutral',
                              'SHOT_RIM_LAYUP': 'Neutral',
                              'SHOT_TOUCH_FLOATER': 'Neutral',
                              'TO_HANDLE_LOSS': 'Neutral'}},
 '블리츠-트랩': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'Neutral',
                    'PASS_KICKOUT': 'Neutral',
                    'SHOT_RIM_CONTACT': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'Neutral',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_HANDLE_LOSS': 'Neutral'},
            'DHO': {'FOUL_DRAW_JUMPER': 'tight',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_EXTRA': 'weak',
                    'PASS_KICKOUT': 'weak',
                    'SHOT_3_CS': 'weak',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'Neutral',
                    'TO_HANDLE_LOSS': 'tight'},
            'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'weak',
                      'PASS_KICKOUT': 'weak',
                      'SHOT_3_OD': 'tight',
                      'SHOT_MID_PU': 'tight',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'tight',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_CHARGE': 'Neutral',
                      'TO_HANDLE_LOSS': 'tight'},
            'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_SKIP': 'Neutral',
                          'SHOT_3_CS': 'weak',
                          'SHOT_MID_CS': 'Neutral'},
            'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                         'PASS_EXTRA': 'Neutral',
                         'PASS_KICKOUT': 'Neutral',
                         'SHOT_3_CS': 'Neutral',
                         'SHOT_MID_CS': 'tight'},
            'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_SKIP': 'Neutral',
                        'SHOT_3_CS': 'weak',
                        'SHOT_MID_CS': 'Neutral'},
            'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                    'FOUL_DRAW_RIM': 'Neutral',
                    'PASS_KICKOUT': 'weak',
                    'PASS_SHORTROLL': 'weak',
                    'SHOT_3_CS': 'weak',
                    'SHOT_3_OD': 'tight',
                    'SHOT_MID_PU': 'tight',
                    'SHOT_RIM_DUNK': 'Neutral',
                    'SHOT_RIM_LAYUP': 'tight',
                    'SHOT_TOUCH_FLOATER': 'tight',
                    'TO_HANDLE_LOSS': 'tight'},
            'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                       'PASS_EXTRA': 'weak',
                       'PASS_KICKOUT': 'weak',
                       'PASS_SKIP': 'weak',
                       'SHOT_POST': 'tight',
                       'SHOT_RIM_CONTACT': 'tight',
                       'TO_HANDLE_LOSS': 'tight'},
            'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'Neutral', 'SHOT_MID_CS': 'Neutral'},
            'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                                'PASS_EXTRA': 'Neutral',
                                'PASS_KICKOUT': 'Neutral',
                                'SHOT_3_CS': 'Neutral',
                                'SHOT_3_OD': 'Neutral',
                                'SHOT_RIM_CONTACT': 'Neutral',
                                'SHOT_RIM_DUNK': 'Neutral',
                                'SHOT_RIM_LAYUP': 'Neutral',
                                'SHOT_TOUCH_FLOATER': 'Neutral',
                                'TO_HANDLE_LOSS': 'Neutral'}},
 '아이스 픽앤롤': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                     'PASS_EXTRA': 'Neutral',
                     'PASS_KICKOUT': 'Neutral',
                     'SHOT_RIM_CONTACT': 'Neutral',
                     'SHOT_RIM_DUNK': 'Neutral',
                     'SHOT_RIM_LAYUP': 'Neutral',
                     'SHOT_TOUCH_FLOATER': 'Neutral',
                     'TO_HANDLE_LOSS': 'Neutral'},
             'DHO': {'FOUL_DRAW_JUMPER': 'Neutral',
                     'FOUL_DRAW_RIM': 'Neutral',
                     'PASS_EXTRA': 'Neutral',
                     'PASS_KICKOUT': 'Neutral',
                     'SHOT_3_CS': 'Neutral',
                     'SHOT_3_OD': 'tight',
                     'SHOT_MID_PU': 'Neutral',
                     'SHOT_RIM_DUNK': 'Neutral',
                     'SHOT_RIM_LAYUP': 'Neutral',
                     'SHOT_TOUCH_FLOATER': 'Neutral',
                     'TO_HANDLE_LOSS': 'Neutral'},
             'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                       'PASS_EXTRA': 'Neutral',
                       'PASS_KICKOUT': 'Neutral',
                       'SHOT_3_OD': 'tight',
                       'SHOT_MID_PU': 'Neutral',
                       'SHOT_RIM_CONTACT': 'tight',
                       'SHOT_RIM_DUNK': 'Neutral',
                       'SHOT_RIM_LAYUP': 'tight',
                       'SHOT_TOUCH_FLOATER': 'Neutral',
                       'TO_CHARGE': 'Neutral',
                       'TO_HANDLE_LOSS': 'Neutral'},
             'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                           'PASS_EXTRA': 'Neutral',
                           'PASS_SKIP': 'Neutral',
                           'SHOT_3_CS': 'Neutral',
                           'SHOT_MID_CS': 'Neutral'},
             'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_KICKOUT': 'Neutral',
                          'SHOT_3_CS': 'Neutral',
                          'SHOT_MID_CS': 'Neutral'},
             'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                         'PASS_EXTRA': 'Neutral',
                         'PASS_SKIP': 'Neutral',
                         'SHOT_3_CS': 'Neutral',
                         'SHOT_MID_CS': 'Neutral'},
             'PnR': {'FOUL_DRAW_JUMPER': 'Neutral',
                     'FOUL_DRAW_RIM': 'tight',
                     'PASS_KICKOUT': 'Neutral',
                     'PASS_SHORTROLL': 'tight',
                     'SHOT_3_CS': 'Neutral',
                     'SHOT_3_OD': 'tight',
                     'SHOT_MID_PU': 'Neutral',
                     'SHOT_RIM_DUNK': 'tight',
                     'SHOT_RIM_LAYUP': 'tight',
                     'SHOT_TOUCH_FLOATER': 'tight',
                     'TO_HANDLE_LOSS': 'Neutral'},
             'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_KICKOUT': 'Neutral',
                        'PASS_SKIP': 'Neutral',
                        'SHOT_POST': 'Neutral',
                        'SHOT_RIM_CONTACT': 'Neutral',
                        'TO_HANDLE_LOSS': 'Neutral'},
             'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'Neutral', 'SHOT_MID_CS': 'Neutral'},
             'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                                 'PASS_EXTRA': 'Neutral',
                                 'PASS_KICKOUT': 'Neutral',
                                 'SHOT_3_CS': 'Neutral',
                                 'SHOT_3_OD': 'Neutral',
                                 'SHOT_RIM_CONTACT': 'Neutral',
                                 'SHOT_RIM_DUNK': 'Neutral',
                                 'SHOT_RIM_LAYUP': 'Neutral',
                                 'SHOT_TOUCH_FLOATER': 'Neutral',
                                 'TO_HANDLE_LOSS': 'Neutral'}},
 '올-스위치': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                   'PASS_EXTRA': 'Neutral',
                   'PASS_KICKOUT': 'Neutral',
                   'SHOT_RIM_CONTACT': 'Neutral',
                   'SHOT_RIM_DUNK': 'Neutral',
                   'SHOT_RIM_LAYUP': 'Neutral',
                   'SHOT_TOUCH_FLOATER': 'Neutral',
                   'TO_HANDLE_LOSS': 'Neutral'},
           'DHO': {'FOUL_DRAW_JUMPER': 'tight',
                   'FOUL_DRAW_RIM': 'Neutral',
                   'PASS_EXTRA': 'Neutral',
                   'PASS_KICKOUT': 'Neutral',
                   'SHOT_3_CS': 'tight',
                   'SHOT_3_OD': 'Neutral',
                   'SHOT_MID_PU': 'Neutral',
                   'SHOT_RIM_DUNK': 'Neutral',
                   'SHOT_RIM_LAYUP': 'Neutral',
                   'SHOT_TOUCH_FLOATER': 'Neutral',
                   'TO_HANDLE_LOSS': 'Neutral'},
           'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                     'PASS_EXTRA': 'Neutral',
                     'PASS_KICKOUT': 'Neutral',
                     'SHOT_3_OD': 'Neutral',
                     'SHOT_MID_PU': 'Neutral',
                     'SHOT_RIM_CONTACT': 'Neutral',
                     'SHOT_RIM_DUNK': 'Neutral',
                     'SHOT_RIM_LAYUP': 'Neutral',
                     'SHOT_TOUCH_FLOATER': 'Neutral',
                     'TO_CHARGE': 'tight',
                     'TO_HANDLE_LOSS': 'Neutral'},
           'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                         'PASS_EXTRA': 'Neutral',
                         'PASS_SKIP': 'Neutral',
                         'SHOT_3_CS': 'Neutral',
                         'SHOT_MID_CS': 'Neutral'},
           'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_KICKOUT': 'Neutral',
                        'SHOT_3_CS': 'Neutral',
                        'SHOT_MID_CS': 'Neutral'},
           'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                       'PASS_EXTRA': 'Neutral',
                       'PASS_SKIP': 'Neutral',
                       'SHOT_3_CS': 'Neutral',
                       'SHOT_MID_CS': 'Neutral'},
           'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                   'FOUL_DRAW_RIM': 'Neutral',
                   'PASS_KICKOUT': 'Neutral',
                   'PASS_SHORTROLL': 'Neutral',
                   'SHOT_3_CS': 'Neutral',
                   'SHOT_3_OD': 'Neutral',
                   'SHOT_MID_PU': 'Neutral',
                   'SHOT_RIM_DUNK': 'Neutral',
                   'SHOT_RIM_LAYUP': 'Neutral',
                   'SHOT_TOUCH_FLOATER': 'Neutral',
                   'TO_HANDLE_LOSS': 'Neutral'},
           'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'PASS_SKIP': 'Neutral',
                      'SHOT_POST': 'Neutral',
                      'SHOT_RIM_CONTACT': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
           'SpotUp': {'FOUL_DRAW_JUMPER': 'tight', 'SHOT_3_CS': 'Neutral', 'SHOT_MID_CS': 'Neutral'},
           'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                               'PASS_EXTRA': 'Neutral',
                               'PASS_KICKOUT': 'Neutral',
                               'SHOT_3_CS': 'Neutral',
                               'SHOT_3_OD': 'Neutral',
                               'SHOT_RIM_CONTACT': 'Neutral',
                               'SHOT_RIM_DUNK': 'Neutral',
                               'SHOT_RIM_LAYUP': 'Neutral',
                               'SHOT_TOUCH_FLOATER': 'Neutral',
                               'TO_HANDLE_LOSS': 'Neutral'}},
 '헷지-쇼앤리커버': {'Cut': {'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'SHOT_RIM_CONTACT': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'Neutral',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'Neutral'},
              'DHO': {'FOUL_DRAW_JUMPER': 'tight',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_EXTRA': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'SHOT_3_CS': 'Neutral',
                      'SHOT_3_OD': 'tight',
                      'SHOT_MID_PU': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'Neutral',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'tight'},
              'Drive': {'FOUL_DRAW_RIM': 'Neutral',
                        'PASS_EXTRA': 'Neutral',
                        'PASS_KICKOUT': 'Neutral',
                        'SHOT_3_OD': 'tight',
                        'SHOT_MID_PU': 'tight',
                        'SHOT_RIM_CONTACT': 'tight',
                        'SHOT_RIM_DUNK': 'Neutral',
                        'SHOT_RIM_LAYUP': 'tight',
                        'SHOT_TOUCH_FLOATER': 'Neutral',
                        'TO_CHARGE': 'Neutral',
                        'TO_HANDLE_LOSS': 'tight'},
              'ExtraPass': {'FOUL_DRAW_JUMPER': 'Neutral',
                            'PASS_EXTRA': 'Neutral',
                            'PASS_SKIP': 'Neutral',
                            'SHOT_3_CS': 'Neutral',
                            'SHOT_MID_CS': 'Neutral'},
              'HornsSet': {'FOUL_DRAW_JUMPER': 'Neutral',
                           'PASS_EXTRA': 'Neutral',
                           'PASS_KICKOUT': 'Neutral',
                           'SHOT_3_CS': 'Neutral',
                           'SHOT_MID_CS': 'tight'},
              'Kickout': {'FOUL_DRAW_JUMPER': 'Neutral',
                          'PASS_EXTRA': 'Neutral',
                          'PASS_SKIP': 'Neutral',
                          'SHOT_3_CS': 'Neutral',
                          'SHOT_MID_CS': 'Neutral'},
              'PnR': {'FOUL_DRAW_JUMPER': 'tight',
                      'FOUL_DRAW_RIM': 'Neutral',
                      'PASS_KICKOUT': 'Neutral',
                      'PASS_SHORTROLL': 'weak',
                      'SHOT_3_CS': 'Neutral',
                      'SHOT_3_OD': 'tight',
                      'SHOT_MID_PU': 'tight',
                      'SHOT_RIM_DUNK': 'Neutral',
                      'SHOT_RIM_LAYUP': 'Neutral',
                      'SHOT_TOUCH_FLOATER': 'Neutral',
                      'TO_HANDLE_LOSS': 'tight'},
              'PostUp': {'FOUL_DRAW_POST': 'Neutral',
                         'PASS_EXTRA': 'Neutral',
                         'PASS_KICKOUT': 'Neutral',
                         'PASS_SKIP': 'Neutral',
                         'SHOT_POST': 'Neutral',
                         'SHOT_RIM_CONTACT': 'tight',
                         'TO_HANDLE_LOSS': 'Neutral'},
              'SpotUp': {'FOUL_DRAW_JUMPER': 'Neutral', 'SHOT_3_CS': 'Neutral', 'SHOT_MID_CS': 'Neutral'},
              'TransitionEarly': {'FOUL_DRAW_RIM': 'Neutral',
                                  'PASS_EXTRA': 'Neutral',
                                  'PASS_KICKOUT': 'Neutral',
                                  'SHOT_3_CS': 'Neutral',
                                  'SHOT_3_OD': 'Neutral',
                                  'SHOT_RIM_CONTACT': 'Neutral',
                                  'SHOT_RIM_DUNK': 'Neutral',
                                  'SHOT_RIM_LAYUP': 'Neutral',
                                  'SHOT_TOUCH_FLOATER': 'Neutral',
                                  'TO_HANDLE_LOSS': 'Neutral'}}}

# scheme -> role -> stat_profile (stat -> weight)
ROLE_STAT_PROFILES: Dict[str, Dict[str, Dict[str, float]]] = {'2-3 존디펜스': {'Zone_Bottom_Left': {'DEF_HELP': 0.15,
                                   'DEF_POST': 0.15,
                                   'DEF_RIM': 0.3,
                                   'ENDURANCE': 0.05,
                                   'PHYSICAL': 0.1,
                                   'REB_DR': 0.25},
              'Zone_Bottom_Right': {'DEF_HELP': 0.15,
                                    'DEF_POST': 0.15,
                                    'DEF_RIM': 0.3,
                                    'ENDURANCE': 0.05,
                                    'PHYSICAL': 0.1,
                                    'REB_DR': 0.25},
              'Zone_Bottom_Center': {'DEF_HELP': 0.10,
                                    'DEF_POST': 0.2,
                                    'DEF_RIM': 0.3,
                                    'ENDURANCE': 0.05,
                                    'PHYSICAL': 0.1,
                                    'REB_DR': 0.25},
              'Zone_Top_Left': {'DEF_HELP': 0.3, 'DEF_POA': 0.25, 'DEF_STEAL': 0.2, 'ENDURANCE': 0.15, 'PHYSICAL': 0.1},
              'Zone_Top_Right': {'DEF_HELP': 0.3,
                                 'DEF_POA': 0.25,
                                 'DEF_STEAL': 0.2,
                                 'ENDURANCE': 0.15,
                                 'PHYSICAL': 0.1}},
              
 'drop': {'Lowman_Helper': {'DEF_HELP': 0.35, 'DEF_RIM': 0.25, 'DEF_STEAL': 0.1, 'PHYSICAL': 0.15, 'REB_DR': 0.15},
          'Nail_Helper': {'DEF_HELP': 0.45, 'DEF_POA': 0.2, 'DEF_STEAL': 0.15, 'ENDURANCE': 0.1, 'PHYSICAL': 0.1},
          'PnR_Cover_Big_Drop': {'DEF_HELP': 0.15,
                                 'DEF_POST': 0.15,
                                 'DEF_RIM': 0.35,
                                 'ENDURANCE': 0.05,
                                 'PHYSICAL': 0.1,
                                 'REB_DR': 0.2},
          'PnR_POA_Defender': {'DEF_HELP': 0.1, 'DEF_POA': 0.45, 'DEF_STEAL': 0.1, 'ENDURANCE': 0.15, 'PHYSICAL': 0.2},
          'Weakside_Rotator': {'DEF_HELP': 0.45,
                               'DEF_POA': 0.15,
                               'DEF_STEAL': 0.1,
                               'ENDURANCE': 0.15,
                               'PHYSICAL': 0.05,
                               'REB_DR': 0.1}},
 '블리츠-트랩': {'Lowman_Helper': {'DEF_HELP': 0.35,
                              'DEF_RIM': 0.25,
                              'DEF_STEAL': 0.05,
                              'ENDURANCE': 0.15,
                              'PHYSICAL': 0.1,
                              'REB_DR': 0.1},
            'Nail_Helper': {'DEF_HELP': 0.4, 'DEF_POA': 0.15, 'DEF_STEAL': 0.2, 'ENDURANCE': 0.15, 'PHYSICAL': 0.1},
            'PnR_Cover_Big_Blitz': {'DEF_HELP': 0.2,
                                    'DEF_POA': 0.2,
                                    'DEF_RIM': 0.05,
                                    'DEF_STEAL': 0.2,
                                    'ENDURANCE': 0.2,
                                    'PHYSICAL': 0.1,
                                    'REB_DR': 0.05},
            'PnR_POA_Blitz': {'DEF_HELP': 0.1, 'DEF_POA': 0.3, 'DEF_STEAL': 0.25, 'ENDURANCE': 0.2, 'PHYSICAL': 0.15},
            'Weakside_Rotator': {'DEF_HELP': 0.35,
                                 'DEF_POA': 0.15,
                                 'DEF_STEAL': 0.15,
                                 'ENDURANCE': 0.25,
                                 'PHYSICAL': 0.05,
                                 'REB_DR': 0.05}},
 '아이스 픽앤롤': {'Lowman_Helper': {'DEF_HELP': 0.3,
                               'DEF_RIM': 0.25,
                               'DEF_STEAL': 0.05,
                               'ENDURANCE': 0.15,
                               'PHYSICAL': 0.1,
                               'REB_DR': 0.15},
             'Nail_Helper': {'DEF_HELP': 0.4, 'DEF_POA': 0.2, 'DEF_STEAL': 0.15, 'ENDURANCE': 0.15, 'PHYSICAL': 0.1},
             'PnR_Cover_Big_Ice': {'DEF_HELP': 0.2,
                                   'DEF_POST': 0.1,
                                   'DEF_RIM': 0.3,
                                   'ENDURANCE': 0.1,
                                   'PHYSICAL': 0.15,
                                   'REB_DR': 0.15},
             'PnR_POA_Ice': {'DEF_HELP': 0.1, 'DEF_POA': 0.45, 'DEF_STEAL': 0.05, 'ENDURANCE': 0.2, 'PHYSICAL': 0.2},
             'Strongside_Corner_Defender': {'DEF_HELP': 0.35,
                                            'DEF_POA': 0.25,
                                            'DEF_STEAL': 0.15,
                                            'ENDURANCE': 0.15,
                                            'PHYSICAL': 0.1}},
 '올-스위치': {'Backline_Anchor': {'DEF_HELP': 0.25,
                               'DEF_POST': 0.1,
                               'DEF_RIM': 0.3,
                               'ENDURANCE': 0.05,
                               'PHYSICAL': 0.1,
                               'REB_DR': 0.2},
           'PnR_Cover_Big_Switch': {'DEF_HELP': 0.1,
                                    'DEF_POA': 0.3,
                                    'DEF_POST': 0.15,
                                    'DEF_RIM': 0.15,
                                    'ENDURANCE': 0.1,
                                    'PHYSICAL': 0.2},
           'PnR_POA_Switch': {'DEF_HELP': 0.15,
                              'DEF_POA': 0.3,
                              'DEF_POST': 0.2,
                              'DEF_STEAL': 0.05,
                              'ENDURANCE': 0.1,
                              'PHYSICAL': 0.2},
           'Switch_Wing_Strong': {'DEF_HELP': 0.25,
                                  'DEF_POA': 0.3,
                                  'DEF_STEAL': 0.15,
                                  'ENDURANCE': 0.15,
                                  'PHYSICAL': 0.1,
                                  'REB_DR': 0.05},
           'Switch_Wing_Weak': {'DEF_HELP': 0.3,
                                'DEF_POA': 0.2,
                                'DEF_STEAL': 0.1,
                                'ENDURANCE': 0.1,
                                'PHYSICAL': 0.1,
                                'REB_DR': 0.2}},
 '헷지-쇼앤리커버': {'Lowman_Helper': {'DEF_HELP': 0.35,
                                'DEF_RIM': 0.2,
                                'DEF_STEAL': 0.05,
                                'ENDURANCE': 0.15,
                                'PHYSICAL': 0.1,
                                'REB_DR': 0.15},
              'Nail_Helper': {'DEF_HELP': 0.4, 'DEF_POA': 0.2, 'DEF_STEAL': 0.15, 'ENDURANCE': 0.15, 'PHYSICAL': 0.1},
              'PnR_Cover_Big_HedgeRecover': {'DEF_HELP': 0.15,
                                             'DEF_POA': 0.25,
                                             'DEF_RIM': 0.15,
                                             'DEF_STEAL': 0.05,
                                             'ENDURANCE': 0.2,
                                             'PHYSICAL': 0.15,
                                             'REB_DR': 0.05},
              'PnR_POA_Defender': {'DEF_HELP': 0.1,
                                   'DEF_POA': 0.45,
                                   'DEF_STEAL': 0.1,
                                   'ENDURANCE': 0.2,
                                   'PHYSICAL': 0.15},
              'Weakside_Rotator': {'DEF_HELP': 0.4,
                                   'DEF_POA': 0.15,
                                   'DEF_STEAL': 0.1,
                                   'ENDURANCE': 0.2,
                                   'PHYSICAL': 0.05,
                                   'REB_DR': 0.1}}}

# group_id -> scheme -> role -> weight (role involvement weights)
GROUP_SCHEME_ROLE_WEIGHTS: Dict[str, Dict[str, Dict[str, float]]] = {'catch_shoot': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                              'Zone_Bottom_Right': 0.2,
                              'Zone_Bottom_Center': 0.2,
                              'Zone_Top_Left': 0.2,
                              'Zone_Top_Right': 0.2},
                 'drop': {'Lowman_Helper': 0.15,
                          'Nail_Helper': 0.25,
                          'PnR_Cover_Big_Drop': 0.1,
                          'PnR_POA_Defender': 0.15,
                          'Weakside_Rotator': 0.35},
                 '블리츠-트랩': {'Lowman_Helper': 0.2,
                            'Nail_Helper': 0.25,
                            'PnR_Cover_Big_Blitz': 0.15,
                            'PnR_POA_Blitz': 0.1,
                            'Weakside_Rotator': 0.3},
                 '아이스 픽앤롤': {'Lowman_Helper': 0.15,
                             'Nail_Helper': 0.25,
                             'PnR_Cover_Big_Ice': 0.15,
                             'PnR_POA_Ice': 0.15,
                             'Strongside_Corner_Defender': 0.3},
                 '올-스위치': {'Backline_Anchor': 0.2,
                           'PnR_Cover_Big_Switch': 0.15,
                           'PnR_POA_Switch': 0.2,
                           'Switch_Wing_Strong': 0.2,
                           'Switch_Wing_Weak': 0.25},
                 '헷지-쇼앤리커버': {'Lowman_Helper': 0.15,
                              'Nail_Helper': 0.25,
                              'PnR_Cover_Big_HedgeRecover': 0.15,
                              'PnR_POA_Defender': 0.15,
                              'Weakside_Rotator': 0.3}},
 'paint_non_rim': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                                'Zone_Bottom_Right': 0.2,
                                'Zone_Bottom_Center': 0.25,
                                'Zone_Top_Left': 0.175,
                                'Zone_Top_Right': 0.175},
                   'drop': {'Lowman_Helper': 0.15,
                            'Nail_Helper': 0.2,
                            'PnR_Cover_Big_Drop': 0.2,
                            'PnR_POA_Defender': 0.35,
                            'Weakside_Rotator': 0.1},
                   '블리츠-트랩': {'Lowman_Helper': 0.2,
                              'Nail_Helper': 0.2,
                              'PnR_Cover_Big_Blitz': 0.15,
                              'PnR_POA_Blitz': 0.25,
                              'Weakside_Rotator': 0.2},
                   '아이스 픽앤롤': {'Lowman_Helper': 0.15,
                               'Nail_Helper': 0.2,
                               'PnR_Cover_Big_Ice': 0.25,
                               'PnR_POA_Ice': 0.3,
                               'Strongside_Corner_Defender': 0.1},
                   '올-스위치': {'Backline_Anchor': 0.2,
                             'PnR_Cover_Big_Switch': 0.2,
                             'PnR_POA_Switch': 0.3,
                             'Switch_Wing_Strong': 0.15,
                             'Switch_Wing_Weak': 0.15},
                   '헷지-쇼앤리커버': {'Lowman_Helper': 0.2,
                                'Nail_Helper': 0.2,
                                'PnR_Cover_Big_HedgeRecover': 0.25,
                                'PnR_POA_Defender': 0.25,
                                'Weakside_Rotator': 0.1}},
 'pass_extra': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.26,
                             'Zone_Bottom_Right': 0.26,
                             'Zone_Top_Left': 0.21,
                             'Zone_Bottom_Center': 0.05,
                             'Zone_Top_Right': 0.22},
                'drop': {'Lowman_Helper': 0.15,
                         'Nail_Helper': 0.3,
                         'PnR_Cover_Big_Drop': 0.1,
                         'PnR_POA_Defender': 0.1,
                         'Weakside_Rotator': 0.35},
                '블리츠-트랩': {'Lowman_Helper': 0.2,
                           'Nail_Helper': 0.3,
                           'PnR_Cover_Big_Blitz': 0.05,
                           'PnR_POA_Blitz': 0.1,
                           'Weakside_Rotator': 0.35},
                '아이스 픽앤롤': {'Lowman_Helper': 0.2,
                            'Nail_Helper': 0.3,
                            'PnR_Cover_Big_Ice': 0.1,
                            'PnR_POA_Ice': 0.1,
                            'Strongside_Corner_Defender': 0.3},
                '올-스위치': {'Backline_Anchor': 0.2,
                          'PnR_Cover_Big_Switch': 0.15,
                          'PnR_POA_Switch': 0.15,
                          'Switch_Wing_Strong': 0.2,
                          'Switch_Wing_Weak': 0.3},
                '헷지-쇼앤리커버': {'Lowman_Helper': 0.15,
                             'Nail_Helper': 0.3,
                             'PnR_Cover_Big_HedgeRecover': 0.15,
                             'PnR_POA_Defender': 0.1,
                             'Weakside_Rotator': 0.3}},
 'pass_kickout': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.22,
                               'Zone_Bottom_Right': 0.22,
                               'Zone_Top_Left': 0.27,
                               'Zone_Bottom_Center': 0.02,
                               'Zone_Top_Right': 0.27},
                  'drop': {'Lowman_Helper': 0.15,
                           'Nail_Helper': 0.3,
                           'PnR_Cover_Big_Drop': 0.1,
                           'PnR_POA_Defender': 0.15,
                           'Weakside_Rotator': 0.3},
                  '블리츠-트랩': {'Lowman_Helper': 0.1,
                             'Nail_Helper': 0.3,
                             'PnR_Cover_Big_Blitz': 0.15,
                             'PnR_POA_Blitz': 0.15,
                             'Weakside_Rotator': 0.3},
                  '아이스 픽앤롤': {'Lowman_Helper': 0.2,
                              'Nail_Helper': 0.3,
                              'PnR_Cover_Big_Ice': 0.1,
                              'PnR_POA_Ice': 0.15,
                              'Strongside_Corner_Defender': 0.25},
                  '올-스위치': {'Backline_Anchor': 0.2,
                            'PnR_Cover_Big_Switch': 0.15,
                            'PnR_POA_Switch': 0.2,
                            'Switch_Wing_Strong': 0.2,
                            'Switch_Wing_Weak': 0.25},
                  '헷지-쇼앤리커버': {'Lowman_Helper': 0.1,
                               'Nail_Helper': 0.3,
                               'PnR_Cover_Big_HedgeRecover': 0.2,
                               'PnR_POA_Defender': 0.15,
                               'Weakside_Rotator': 0.25}},
 'pass_shortroll': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                                 'Zone_Bottom_Right': 0.2,
                                 'Zone_Top_Left': 0.15,
                                 'Zone_Bottom_Center': 0.3,
                                 'Zone_Top_Right': 0.15},
                    'drop': {'Lowman_Helper': 0.3,
                             'Nail_Helper': 0.25,
                             'PnR_Cover_Big_Drop': 0.2,
                             'PnR_POA_Defender': 0.1,
                             'Weakside_Rotator': 0.15},
                    '블리츠-트랩': {'Lowman_Helper': 0.2,
                               'Nail_Helper': 0.2,
                               'PnR_Cover_Big_Blitz': 0.25,
                               'PnR_POA_Blitz': 0.2,
                               'Weakside_Rotator': 0.15},
                    '아이스 픽앤롤': {'Lowman_Helper': 0.25,
                                'Nail_Helper': 0.2,
                                'PnR_Cover_Big_Ice': 0.25,
                                'PnR_POA_Ice': 0.2,
                                'Strongside_Corner_Defender': 0.1},
                    '올-스위치': {'Backline_Anchor': 0.3,
                              'PnR_Cover_Big_Switch': 0.2,
                              'PnR_POA_Switch': 0.2,
                              'Switch_Wing_Strong': 0.15,
                              'Switch_Wing_Weak': 0.15},
                    '헷지-쇼앤리커버': {'Lowman_Helper': 0.25,
                                 'Nail_Helper': 0.2,
                                 'PnR_Cover_Big_HedgeRecover': 0.25,
                                 'PnR_POA_Defender': 0.15,
                                 'Weakside_Rotator': 0.15}},
 'pass_skip': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.18,
                            'Zone_Bottom_Right': 0.18,
                            'Zone_Top_Left': 0.28,
                            'Zone_Bottom_Center': 0.08,
                            'Zone_Top_Right': 0.28},
               'drop': {'Lowman_Helper': 0.15,
                        'Nail_Helper': 0.3,
                        'PnR_Cover_Big_Drop': 0.1,
                        'PnR_POA_Defender': 0.15,
                        'Weakside_Rotator': 0.3},
               '블리츠-트랩': {'Lowman_Helper': 0.1,
                          'Nail_Helper': 0.35,
                          'PnR_Cover_Big_Blitz': 0.1,
                          'PnR_POA_Blitz': 0.15,
                          'Weakside_Rotator': 0.3},
               '아이스 픽앤롤': {'Lowman_Helper': 0.2,
                           'Nail_Helper': 0.35,
                           'PnR_Cover_Big_Ice': 0.1,
                           'PnR_POA_Ice': 0.1,
                           'Strongside_Corner_Defender': 0.25},
               '올-스위치': {'Backline_Anchor': 0.15,
                         'PnR_Cover_Big_Switch': 0.15,
                         'PnR_POA_Switch': 0.15,
                         'Switch_Wing_Strong': 0.25,
                         'Switch_Wing_Weak': 0.3},
               '헷지-쇼앤리커버': {'Lowman_Helper': 0.1,
                            'Nail_Helper': 0.3,
                            'PnR_Cover_Big_HedgeRecover': 0.2,
                            'PnR_POA_Defender': 0.1,
                            'Weakside_Rotator': 0.3}},
 'pullup': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.15,
                         'Zone_Bottom_Right': 0.15,
                         'Zone_Bottom_Center': 0.1,
                         'Zone_Top_Left': 0.3,
                         'Zone_Top_Right': 0.3},
            'drop': {'Lowman_Helper': 0.05,
                     'Nail_Helper': 0.15,
                     'PnR_Cover_Big_Drop': 0.15,
                     'PnR_POA_Defender': 0.55,
                     'Weakside_Rotator': 0.1},
            '블리츠-트랩': {'Lowman_Helper': 0.1,
                       'Nail_Helper': 0.15,
                       'PnR_Cover_Big_Blitz': 0.25,
                       'PnR_POA_Blitz': 0.35,
                       'Weakside_Rotator': 0.15},
            '아이스 픽앤롤': {'Lowman_Helper': 0.1,
                        'Nail_Helper': 0.15,
                        'PnR_Cover_Big_Ice': 0.2,
                        'PnR_POA_Ice': 0.45,
                        'Strongside_Corner_Defender': 0.1},
            '올-스위치': {'Backline_Anchor': 0.1,
                      'PnR_Cover_Big_Switch': 0.2,
                      'PnR_POA_Switch': 0.35,
                      'Switch_Wing_Strong': 0.2,
                      'Switch_Wing_Weak': 0.15},
            '헷지-쇼앤리커버': {'Lowman_Helper': 0.1,
                         'Nail_Helper': 0.15,
                         'PnR_Cover_Big_HedgeRecover': 0.25,
                         'PnR_POA_Defender': 0.35,
                         'Weakside_Rotator': 0.15}},
 'rim_finish': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.25,
                             'Zone_Bottom_Right': 0.25,
                             'Zone_Bottom_Center': 0.3,
                             'Zone_Top_Left': 0.1,
                             'Zone_Top_Right': 0.1},
                'drop': {'Lowman_Helper': 0.25,
                         'Nail_Helper': 0.05,
                         'PnR_Cover_Big_Drop': 0.45,
                         'PnR_POA_Defender': 0.2,
                         'Weakside_Rotator': 0.05},
                '블리츠-트랩': {'Lowman_Helper': 0.3,
                           'Nail_Helper': 0.2,
                           'PnR_Cover_Big_Blitz': 0.15,
                           'PnR_POA_Blitz': 0.15,
                           'Weakside_Rotator': 0.2},
                '아이스 픽앤롤': {'Lowman_Helper': 0.2,
                            'Nail_Helper': 0.1,
                            'PnR_Cover_Big_Ice': 0.35,
                            'PnR_POA_Ice': 0.25,
                            'Strongside_Corner_Defender': 0.1},
                '올-스위치': {'Backline_Anchor': 0.35,
                          'PnR_Cover_Big_Switch': 0.2,
                          'PnR_POA_Switch': 0.2,
                          'Switch_Wing_Strong': 0.1,
                          'Switch_Wing_Weak': 0.15},
                '헷지-쇼앤리커버': {'Lowman_Helper': 0.25,
                             'Nail_Helper': 0.15,
                             'PnR_Cover_Big_HedgeRecover': 0.3,
                             'PnR_POA_Defender': 0.2,
                             'Weakside_Rotator': 0.1}},
 'to_charge': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                            'Zone_Bottom_Right': 0.2,
                            'Zone_Bottom_Center': 0.2,
                            'Zone_Top_Left': 0.2,
                            'Zone_Top_Right': 0.2},
               'drop': {'Lowman_Helper': 0.2,
                        'Nail_Helper': 0.3,
                        'PnR_Cover_Big_Drop': 0.1,
                        'PnR_POA_Defender': 0.35,
                        'Weakside_Rotator': 0.05},
               '블리츠-트랩': {'Lowman_Helper': 0.2,
                          'Nail_Helper': 0.35,
                          'PnR_Cover_Big_Blitz': 0.1,
                          'PnR_POA_Blitz': 0.25,
                          'Weakside_Rotator': 0.1},
               '아이스 픽앤롤': {'Lowman_Helper': 0.2,
                           'Nail_Helper': 0.3,
                           'PnR_Cover_Big_Ice': 0.05,
                           'PnR_POA_Ice': 0.35,
                           'Strongside_Corner_Defender': 0.1},
               '올-스위치': {'Backline_Anchor': 0.25,
                         'PnR_Cover_Big_Switch': 0.1,
                         'PnR_POA_Switch': 0.3,
                         'Switch_Wing_Strong': 0.2,
                         'Switch_Wing_Weak': 0.15},
               '헷지-쇼앤리커버': {'Lowman_Helper': 0.2,
                            'Nail_Helper': 0.3,
                            'PnR_Cover_Big_HedgeRecover': 0.1,
                            'PnR_POA_Defender': 0.3,
                            'Weakside_Rotator': 0.1}},
 'to_handle_loss': {'2-3 존디펜스': {'Zone_Bottom_Left': 0.2,
                                 'Zone_Bottom_Right': 0.2,
                                 'Zone_Bottom_Center': 0.1,
                                 'Zone_Top_Left': 0.25,
                                 'Zone_Top_Right': 0.25},
                    'drop': {'Lowman_Helper': 0.05,
                             'Nail_Helper': 0.15,
                             'PnR_Cover_Big_Drop': 0.1,
                             'PnR_POA_Defender': 0.6,
                             'Weakside_Rotator': 0.1},
                    '블리츠-트랩': {'Lowman_Helper': 0.05,
                               'Nail_Helper': 0.15,
                               'PnR_Cover_Big_Blitz': 0.3,
                               'PnR_POA_Blitz': 0.45,
                               'Weakside_Rotator': 0.05},
                    '아이스 픽앤롤': {'Lowman_Helper': 0.1,
                                'Nail_Helper': 0.15,
                                'PnR_Cover_Big_Ice': 0.1,
                                'PnR_POA_Ice': 0.5,
                                'Strongside_Corner_Defender': 0.15},
                    '올-스위치': {'Backline_Anchor': 0.1,
                              'PnR_Cover_Big_Switch': 0.2,
                              'PnR_POA_Switch': 0.4,
                              'Switch_Wing_Strong': 0.2,
                              'Switch_Wing_Weak': 0.1},
                    '헷지-쇼앤리커버': {'Lowman_Helper': 0.1,
                                 'Nail_Helper': 0.15,
                                 'PnR_Cover_Big_HedgeRecover': 0.2,
                                 'PnR_POA_Defender': 0.45,
                                 'Weakside_Rotator': 0.1}}}

# outcome -> group_id (used to choose the role-weight profile)
OUTCOME_TO_GROUP: Dict[str, str] = {'FOUL_DRAW_JUMPER': 'pullup',
 'FOUL_DRAW_POST': 'post_interior',
 'FOUL_DRAW_RIM': 'rim_finish',
 'PASS_EXTRA': 'pass_extra',
 'PASS_KICKOUT': 'pass_kickout',
 'PASS_SHORTROLL': 'pass_shortroll',
 'PASS_SKIP': 'pass_skip',
 'SHOT_3_CS': 'catch_shoot',
 'SHOT_3_OD': 'pullup',
 'SHOT_MID_CS': 'catch_shoot',
 'SHOT_MID_PU': 'pullup',
 'SHOT_POST': 'post_interior',
 'SHOT_RIM_CONTACT': 'rim_finish',
 'SHOT_RIM_DUNK': 'rim_finish',
 'SHOT_RIM_LAYUP': 'rim_finish',
 'SHOT_TOUCH_FLOATER': 'paint_non_rim',
 'TO_BAD_PASS': 'pass_skip',
 'TO_CHARGE': 'to_charge',
 'TO_HANDLE_LOSS': 'to_handle_loss'}

# Groups that should reuse an existing role-weight profile.
GROUP_FALLBACK: Dict[str, str] = {
    # Post/Interior outcomes didn't have their own role-weight block in the source doc.
    # They share very similar tasks (T2/T3/T7/T1) with rim_finish.
    "post_interior": "rim_finish",
}

# Scheme aliases: accept short english ids too.
SCHEME_ALIASES: Dict[str, str] = {
    "drop": "drop",
    "Drop": "drop",
    "Switch_Everything": "올-스위치",
    "Hedge_ShowRecover": "헷지-쇼앤리커버",
    "Blitz_TrapPnR": "블리츠-트랩",
    "ICE_SidePnR": "아이스 픽앤롤",
    "Zone": "2-3 존디펜스",
    "all_switch": "올-스위치",
    "all-switch": "올-스위치",
    "switch": "올-스위치",
    "올-스위치": "올-스위치",
    "hedge": "헷지-쇼앤리커버",
    "hedge-recover": "헷지-쇼앤리커버",
    "헷지-쇼앤리커버": "헷지-쇼앤리커버",
    "blitz": "블리츠-트랩",
    "trap": "블리츠-트랩",
    "blitz-trap": "블리츠-트랩",
    "블리츠-트랩": "블리츠-트랩",
    "ice": "아이스 픽앤롤",
    "아이스": "아이스 픽앤롤",
    "아이스 픽앤롤": "아이스 픽앤롤",
    "zone": "2-3 존디펜스",
    "2-3": "2-3 존디펜스",
    "2-3 zone": "2-3 존디펜스",
    "2-3 존디펜스": "2-3 존디펜스",
}
